name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install GTK4
      run: sudo apt-get install -y libgtk-4-dev
    - name: make all
      run: make all
    - name: make clean
      run: make clean
      
